# jekyll serve --baseurl ""
name: "Web Application Guidelines, v4"
nav:
  - { title: 'Introduction', url: '/' }
  - { title: 'Getting Started', url: '/getting_started/' }
  - { title: 'Grids &amp; Responsive Design', url: '/grids_and_responsive_design/' }
  - { title: 'Navigation &amp; Pagination', url: '/navigation_and_pagination/' }
  - { title: 'Typography &amp; Articles', url: '/typography_and_articles/' }
  - { title: 'Tables', url: '/tables/' }
  - { title: 'Colors', url: '/colors/' }
  - { title: 'Forms, Buttons &amp; Messages', url: '/forms_buttons_and_messages/' }
  - { title: 'Other Page Elements', url: '/other_page_elements/' }

markdown: kramdown
highlighter: pygments
exclude: []
baseurl: /wag-v4
cdn_url: //assets.malmo.se/external/v4
# cdn_url: //www.local.malmo.se:3001/assets
permalink: /:categories/:title
relative_permalinks: false

sass:
  # style: :expanded
  style: :compressed

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
